### ISSUE TITLE
Translation for other languages

### ISSUE THREAD

**Issue by TiagoDanin** [vitordelucca/Reddunt#8]
**Level**: Easy

**Branch**: rs2_release_svc
**Locale**: [Reddunt/blob/rs2_release_svc/Baconit/Strings/*](https://github.com/vitorgrs/Reddunt/tree/rs2_release_svc/Baconit/Strings)

**Laguage-id codes**: [List here](https://www.science.co.il/language/Locale-codes.php)

[Hacktoberfest 2017](https://hacktoberfest.digitalocean.com/) 🎉

**Comment by kRkk** [comment]
I will try

**Comment by erickzhao** [comment]
Hey @TiagoDanin, I can work on fr-FR!

**Comment by kRkk** [comment]
I add pl-PL

**Comment by kRkk** [comment]
I think that `<string>` isn't needed

**Comment by kRkk** [comment]
I think that `<value>` isn't needed

**Comment by TiagoDanin** [comment]
@erickzhao Of course!

**Comment by Yikal** [comment]
I can add de-DE

**Comment by hizkifw** [comment]
Hi, I'll be working on id-ID

**Comment by mbeatrizmagalhaes** [comment]
Hi, @TiagoDanin ! I can add pt-PT

**Comment by Marusyk** [comment]
I'm gonna add Ukrainian

**Comment by guidoPaglie** [comment]
Hi, i can add es-AR

**Comment by impmihai** [comment]
Hi! I can add ro-RO.

**Comment by Arrowfan** [comment]
i can do sv-se

**Comment by feeeper** [comment]
Hi! I'll add ru-RU translation

**Comment by ChristofferNissen** [comment]
Hi! Ill add da (Danish)

**Comment by LauraLaureus** [comment]
I can add es-es

**Comment by xkre** [comment]
Hi, I'll can add ms-MY.
